// pages/teams.tsx
import React, { useEffect, useState } from 'react'
import Sidebar from '../components/layout/Sidebar'
import Header from '../components/layout/Header'
import api from '../lib/api'

interface Member {
  id: number
  name: string
  role: string
}

const TeamsPage: React.FC = () => {
  const [members, setMembers] = useState<Member[]>([])

  useEffect(() => {
    const fetchMembers = async () => {
      const response = await api.get('/teams')
      setMembers(response.data)
    }
    fetchMembers()
  }, [])

  return (
    <div className="flex min-h-screen bg-gray-100 dark:bg-gray-900">
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Header />
        <main className="p-6">
          <h1 className="text-2xl font-bold mb-4">Team Members</h1>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {members.map((member) => (
              <div key={member.id} className="p-4 bg-white dark:bg-gray-800 rounded shadow">
                <h2 className="font-semibold">{member.name}</h2>
                <p>Role: {member.role}</p>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  )
}

export default TeamsPage

// frontend/components/Teams.vue
<template>
  <div class="teams p-4 space-y-6">
    <h2 class="text-xl font-bold">Teams</h2>
    <div class="grid grid-cols-3 gap-4">
      <div v-for="team in teams" :key="team.id" class="team-card p-4 border rounded hover:bg-gray-100 dark:hover:bg-gray-800">
        <h3 class="font-semibold">{{ team.name }}</h3>
        <p class="text-gray-600 dark:text-gray-300">Members: {{ team.members.length }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const teams = ref([
  { id: 1, name: 'Team A', members: ['Alice', 'Bob'] },
  { id: 2, name: 'Team B', members: ['Charlie', 'Dave'] },
  { id: 3, name: 'Team C', members: ['Eve', 'Frank'] }
])
</script>

<style scoped>
.team-card {
  transition: all 0.2s ease-in-out;
}
</style>
