// frontend/components/Header.vue
<template>
  <header class="header">
    <img src="../assets/logo.png" alt="Youkyouk Logo" class="logo" />
    <button @click="$emit('toggle-dark')">Toggle Dark</button>
  </header>
</template>

<script>
export default {
  name: 'Header'
}
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  border-bottom: 1px solid #ddd;
}
.logo { height: 40px; }
</style>

// packages/ui/components/Header.tsx
import React from "react";
import { QuickSearch } from "./QuickSearch";
import { UserDropdown } from "./UserDropdown";

export const Header: React.FC = () => {
  return (
    <header className="flex items-center justify-between p-4 bg-white dark:bg-gray-800 shadow">
      <div className="flex items-center space-x-2">
        <img src="/logo.png" alt="Youkyouk Logo" className="h-8 w-8" />
        <span className="text-xl font-bold text-gray-900 dark:text-white">Youkyouk</span>
      </div>
      <div className="flex-1 mx-4">
        <QuickSearch />
      </div>
      <div className="flex items-center space-x-4">
        <button className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">🛎️</button>
        <button className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">⚙️</button>
        <UserDropdown />
      </div>
    </header>
  );
};
