// frontend/components/seller/layout/header.vue
<template>
  <header class="header">
    <div class="left">
      <button @click="$emit('toggle-sidebar')">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
        </svg>
      </button>
      <h1>{{ title }}</h1>
    </div>
    <div class="right">
      <button @click="$emit('toggle-theme')">
        🌙
      </button>
      <div class="profile">
        <img :src="user.avatar" alt="Avatar"/>
        <span>{{ user.name }}</span>
      </div>
    </div>
  </header>
</template>

<script setup>
import { defineProps } from 'vue'
const props = defineProps({ title: String, user: Object })
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: var(--color-card-bg);
  padding: 10px 20px;
  box-shadow: var(--shadow-card);
}
body.dark-mode .header {
  background-color: var(--color-card-bg-dark);
}
.left { display: flex; align-items: center; gap: 10px; }
.right { display: flex; align-items: center; gap: 20px; }
.profile { display: flex; align-items: center; gap: 10px; }
.profile img { width: 32px; height: 32px; border-radius: 50%; }
.icon { width: 24px; height: 24px; cursor: pointer; }
</style>

// packages/ui/components/Header.tsx
import React from 'react';
import { QuickSearch } from './QuickSearch';
import { UserDropdown } from './UserDropdown';

export const Header: React.FC = () => {
  return (
    <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800 shadow">
      <div className="flex items-center space-x-2">
        <img src="/logo.png" alt="Youkyouk" className="h-8 w-8" />
        <span className="font-bold text-xl text-gray-900 dark:text-white">Youkyouk</span>
      </div>
      <div className="flex-1 px-4">
        <QuickSearch />
      </div>
      <div className="flex items-center space-x-4">
        <button className="p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405M19 13V6a2 2 0 00-2-2H7a2 2 0 00-2 2v7m14 0l-1.405 1.405M5 17h5" />
          </svg>
        </button>
        <UserDropdown />
      </div>
    </header>
  );
};
