// pages/projects.tsx
import React, { useEffect, useState } from 'react'
import Sidebar from '../components/layout/Sidebar'
import Header from '../components/layout/Header'
import api from '../lib/api'

interface Project {
  id: number
  name: string
  status: string
}

const ProjectsPage: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([])

  useEffect(() => {
    const fetchProjects = async () => {
      const response = await api.get('/projects')
      setProjects(response.data)
    }
    fetchProjects()
  }, [])

  return (
    <div className="flex min-h-screen bg-gray-100 dark:bg-gray-900">
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Header />
        <main className="p-6">
          <h1 className="text-2xl font-bold mb-4">Projects</h1>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {projects.map((project) => (
              <div key={project.id} className="p-4 bg-white dark:bg-gray-800 rounded shadow">
                <h2 className="font-semibold">{project.name}</h2>
                <p>Status: {project.status}</p>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  )
}

export default ProjectsPage

// frontend/pages/Projects.vue
<template>
  <div class="projects p-6">
    <h2 class="text-2xl font-bold mb-4">Projects</h2>
    <div class="grid grid-cols-2 gap-4">
      <ProjectCard v-for="project in projects" :key="project.id" :project="project"/>
    </div>
  </div>
</template>

<script>
import ProjectCard from '../components/ProjectCard.vue'

export default {
  components: { ProjectCard },
  data() {
    return {
      projects: [
        { id: 1, name: 'Project Alpha', description: 'Description Alpha', teamName: 'Team A' },
        { id: 2, name: 'Project Beta', description: 'Description Beta', teamName: 'Team B' }
      ]
    }
  }
}
</script>
