// frontend/components/layout/seller/footer.vue
<template>
  <footer class="youkyouk-footer">
    <div class="left">
      <span>© 2025 Youkyouk. All rights reserved.</span>
    </div>
    <div class="right">
      <ul>
        <li><a href="#">Help Center</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms of Service</a></li>
      </ul>
    </div>
  </footer>
</template>

<script setup>
</script>

<style scoped>
.youkyouk-footer {
  display: flex;
  justify-content: space-between;
  padding: 15px 20px;
  background: #1f2937;
  color: #fff;
  font-size: 14px;
}
.youkyouk-footer a { color: #9ca3af; text-decoration: none; margin-left: 15px; }
.youkyouk-footer a:hover { text-decoration: underline; }
</style>

// frontend/components/layout/footer.tsx
import React from 'react'

const Footer: React.FC = () => {
  return (
    <footer className="bg-white dark:bg-gray-900 border-t dark:border-gray-700 p-4 text-center text-sm text-gray-500 dark:text-gray-400">
      <div className="flex flex-col sm:flex-row justify-center items-center space-y-2 sm:space-y-0 sm:space-x-4">
        <span>© 2025 Youkyouk. All rights reserved.</span>
        <a href="#" className="hover:underline">
          Privacy Policy
        </a>
        <a href="#" className="hover:underline">
          Terms of Service
        </a>
        <a href="#" className="hover:underline">
          Contact
        </a>
      </div>
    </footer>
  )
}

export default Footer
