// packages/ui/components/Header.tsx
import React from "react";
import { QuickSearch } from "./QuickSearch";
import { UserDropdown } from "./UserDropdown";

export const Header: React.FC = () => {
  return (
    <header className="flex items-center justify-between p-4 bg-white dark:bg-gray-800 shadow">
      <div className="flex items-center space-x-2">
        <img src="/logo.png" alt="Youkyouk Logo" className="h-8 w-8" />
        <span className="text-xl font-bold text-gray-900 dark:text-white">Youkyouk</span>
      </div>
      <div className="flex-1 mx-4">
        <QuickSearch />
      </div>
      <div className="flex items-center space-x-4">
        <button className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">🛎️</button>
        <button className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">⚙️</button>
        <UserDropdown />
      </div>
    </header>
  );
};

// frontend/components/layout/header.vue
<template>
  <header class="header">
    <div class="logo">Youkyouk</div>
    <div class="actions">
      <button @click="$emit('toggle-sidebar')">
        <i class="youkyouk-icon-menu"></i>
      </button>
      <button @click="$emit('toggle-theme')">
        <i class="youkyouk-icon-sun"></i>
      </button>
      <div class="user-menu">
        <img :src="user.avatar" class="avatar"/>
        <span>{{ user.name }}</span>
      </div>
    </div>
  </header>
</template>

<script setup>
import { defineProps } from 'vue'
const props = defineProps({ user: Object })
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: #1f2937;
  color: white;
  padding: 10px 20px;
}
.avatar { width: 32px; border-radius: 50%; }
.actions button { background: none; border: none; color: white; margin-right: 10px; font-size: 18px; }
</style>
