// frontend/components/Sidebar.vue
<template>
  <aside class="bg-white dark:bg-gray-900 w-64 min-h-screen shadow p-4 flex flex-col">
    <div class="mb-6">
      <img src="/logo.png" alt="Youkyouk Logo" class="h-10 w-10 mx-auto mb-2">
      <h2 class="text-center font-bold text-gray-900 dark:text-white">Youkyouk</h2>
    </div>
    <nav class="flex-1">
      <ul class="space-y-2">
        <li><a href="/dashboard" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Dashboard</a></li>
        <li><a href="/projects" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Projects</a></li>
        <li><a href="/tasks" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Tasks</a></li>
        <li><a href="/teams" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Teams</a></li>
        <li><a href="/users" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Users</a></li>
        <li><a href="/roles" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Roles</a></li>
        <li><a href="/notifications" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Notifications</a></li>
        <li><a href="/reports" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Reports</a></li>
        <li><a href="/settings" class="block px-3 py-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Settings</a></li>
      </ul>
    </nav>
  </aside>
</template>

<script setup>
</script>

<style scoped>
aside {
  transition: all 0.2s ease-in-out;
}
</style>

// frontend/components/layout/sidebar.tsx
import React, { useState } from 'react'
import { HomeIcon, FolderIcon, ChartBarIcon, UsersIcon } from '@heroicons/react/24/outline'

const Sidebar: React.FC = () => {
  const [open, setOpen] = useState(true)
  
  const toggleSidebar = () => setOpen(!open)

  return (
    <aside className={`bg-white dark:bg-gray-900 shadow h-screen transition-all duration-300 ${open ? 'w-64' : 'w-20'}`}>
      <div className="flex items-center justify-between px-4 py-4">
        <span className="text-lg font-bold text-gray-900 dark:text-white">{open ? 'Youkyouk' : 'YK'}</span>
        <button onClick={toggleSidebar} className="p-1 rounded hover:bg-gray-200 dark:hover:bg-gray-700">
          {open ? '<' : '>'}
        </button>
      </div>
      <nav className="mt-6">
        <ul className="space-y-2">
          <li className="flex items-center px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700 cursor-pointer">
            <HomeIcon className="w-6 h-6"/>
            {open && <span className="ml-3">Dashboard</span>}
          </li>
          <li className="flex items-center px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700 cursor-pointer">
            <FolderIcon className="w-6 h-6"/>
            {open && <span className="ml-3">Projects</span>}
          </li>
          <li className="flex items-center px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700 cursor-pointer">
            <ChartBarIcon className="w-6 h-6"/>
            {open && <span className="ml-3">Analytics</span>}
          </li>
          <li className="flex items-center px-4 py-2 hover:bg-gray-200 dark:hover:bg-gray-700 cursor-pointer">
            <UsersIcon className="w-6 h-6"/>
            {open && <span className="ml-3">Team</span>}
          </li>
        </ul>
      </nav>
    </aside>
  )
}

export default Sidebar
