// frontend/components/layout/footer.tsx
import React from 'react'

const Footer: React.FC = () => {
  return (
    <footer className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 py-4 px-6 flex justify-between items-center text-sm text-gray-500 dark:text-gray-400">
      <div>
        © {new Date().getFullYear()} Youkyouk. All rights reserved.
      </div>
      <div className="flex space-x-4">
        <a href="#" className="hover:text-gray-700 dark:hover:text-gray-200">
          About
        </a>
        <a href="#" className="hover:text-gray-700 dark:hover:text-gray-200">
          Privacy
        </a>
        <a href="#" className="hover:text-gray-700 dark:hover:text-gray-200">
          Terms
        </a>
      </div>
    </footer>
  )
}

export default Footer

// frontend/web/components/layout/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-left">
      <span>&copy; {{ currentYear }} Youkyouk. All rights reserved.</span>
    </div>
    <div class="footer-right">
      <a href="#">Privacy</a>
      <a href="#">Terms</a>
      <a href="#">Help</a>
    </div>
  </footer>
</template>

<script>
export default {
  name: "Footer",
  data() {
    return {
      currentYear: new Date().getFullYear()
    };
  }
};
</script>

<style scoped>
.footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background-color: var(--header-bg);
  color: var(--text-color);
  font-family: 'Inter', sans-serif;
  border-top: 1px solid var(--border-color);
}

.footer a {
  margin-left: 16px;
  color: var(--text-color);
  text-decoration: none;
}

.footer a:hover {
  text-decoration: underline;
}
</style>
