// frontend/components/Sidebar.vue
<template>
  <aside class="w-64 bg-gray-100 dark:bg-gray-900 min-h-screen p-4">
    <nav>
      <ul class="space-y-2">
        <li><a href="/dashboard" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Dashboard</a></li>
        <li><a href="/projects" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Projects</a></li>
        <li><a href="/tasks" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Tasks</a></li>
        <li><a href="/teams" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Teams</a></li>
        <li><a href="/users" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Users</a></li>
        <li><a href="/reports" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Reports</a></li>
        <li><a href="/settings" class="block py-2 px-3 rounded hover:bg-gray-200 dark:hover:bg-gray-800">Settings</a></li>
      </ul>
    </nav>
  </aside>
</template>

// apps/web/packages/ui/components/Sidebar.tsx
import React from "react";

export const Sidebar: React.FC = () => {
  return (
    <aside className="w-64 bg-white dark:bg-gray-800 shadow-md h-full">
      <ul className="p-4 space-y-2">
        <li>
          <a href="/" className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">
            Home
          </a>
        </li>
        <li>
          <a href="/about" className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700">
            About
          </a>
        </li>
      </ul>
    </aside>
  );
};
