// apps/web/packages/ui/components/Header.tsx
import React from "react";

interface HeaderProps {
  title: string;
}

export const Header: React.FC<HeaderProps> = ({ title }) => {
  return (
    <header className="flex justify-between items-center mb-6">
      <div className="text-xl font-semibold">{title}</div>
      <div className="flex items-center space-x-4">
        <input
          type="text"
          placeholder="Search..."
          className="border rounded px-2 py-1"
        />
        <button className="px-3 py-1 bg-blue-500 text-white rounded">
          New
        </button>
      </div>
    </header>
  );
};

// frontend/components/layout/seller/header.vue
<template>
  <header class="header">
    <div class="left">
      <input type="text" placeholder="Search products..." v-model="search" />
    </div>
    <div class="right">
      <button @click="toggleDark">🌙</button>
      <img :src="user.avatar || '/default-avatar.png'" class="avatar" />
      <span>{{ user.name }}</span>
    </div>
  </header>
</template>

<script setup>
import { ref, defineProps } from 'vue'
const props = defineProps({ user:Object })
const search = ref('')

const toggleDark = () => {
  document.body.classList.toggle('dark-mode')
}
</script>

<style scoped>
.header { display:flex; justify-content:space-between; align-items:center; padding:1rem; background:#f5f5f5; }
.header .left input { padding:0.5rem; width:200px; }
.header .right { display:flex; align-items:center; gap:0.5rem; }
.avatar { width:32px; height:32px; border-radius:50%; }
</style>
